name: book_stack_design_system
description: "A new Flutter package project."
version: 0.1.0
homepage: null

environment:
  sdk: ">=3.8.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  country_flags: ^3.3.0
  currency_picker: ^2.0.21
  dio: ^5.5.0+1
  either_dart: ^1.0.0
  logger: ^2.2.0
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  google_fonts: ^6.3.1
  equatable: ^2.0.5
  flutter_svg: ^2.2.0
  flutter_widget_from_html: ^0.17.0
  gap: ^3.0.1
  gradient_borders: ^1.0.1
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.3.1
  flutter_gen: ^5.3.1
  json_serializable: ^6.7.1

flutter:
  assets:
    - lib/assets/colors/
    - lib/assets/icons/
    - lib/assets/images/

flutter_gen:
  output: lib/designs/atomic/tokens/src/gen
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: BookStackAssets
  colors:
    enabled: true
    outputs:
      class_name: BookStackColors
    inputs:
      - lib/assets/colors/colors.xml
